-- TAG: PROJ-101
-- SCHEMA: ACCOUNT
-- TYPE: DDL
-- TABLES: ACCOUNT
-- DESCRIPTION: Add STATUS flag to ACCOUNT table
-- BREAKING: N
ALTER TABLE ACCOUNT ADD (STATUS NUMBER(1) DEFAULT 0 NOT NULL);
COMMENT ON COLUMN ACCOUNT.STATUS IS 'Account status flag: 0=inactive, 1=active';
