-- TAG: PROJ-100
-- SCHEMA: ACCOUNT
-- TYPE: DDL
-- TABLES: ACCOUNT
-- DESCRIPTION: Create ACCOUNT table (initial)
-- BREAKING: N

CREATE TABLE ACCOUNT
(
  ID          NUMBER(19)     NOT NULL,
  USERNAME    VARCHAR2(64)   NOT NULL,
  NICKNAME    VARCHAR2(128),
  BALANCE     NUMBER(18,4)   DEFAULT 0 NOT NULL,
  CREATED_AT  TIMESTAMP(6)   DEFAULT SYSTIMESTAMP NOT NULL
);
COMMENT ON TABLE  ACCOUNT          IS 'Per-user account';
COMMENT ON COLUMN ACCOUNT.ID       IS 'Surrogate primary key';
ALTER TABLE ACCOUNT ADD CONSTRAINT ACCOUNT_PK PRIMARY KEY (ID) USING INDEX;
CREATE SEQUENCE SEQACCOUNT
  MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 CACHE 100 NOORDER;
